name: Docker Image Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'etc/**'
      - '*.md'
      - '.github/**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      # TAG_SUFFIX 생성 (오늘 날짜 기준)
      - name: Set build tag
        run: |
          echo "TAG_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # === Streamlit 이미지: jigreg/skk:main-YYYYMMDD ===
      - name: Build and push UI image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: main/Dockerfile
          push: true
          platforms: linux/amd64
          tags: jigreg/skk:main-${{ env.TAG_DATE }}

      # === API 이미지: jigreg/skk:api-YYYYMMDD ===
      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: api/Dockerfile
          push: true
          platforms: linux/amd64
          tags: jigreg/skk:api-${{ env.TAG_DATE }}
